"""Generated by servant.

Capability: reverse a string
Run: call-add303

This file was written by a language model and passed static validation
and a sandboxed test run. A human still reviewed it before install.
"""
from servant.sdk import tool, Tier, ToolError

@tool(
    name="string.reverse",
    tier=Tier.DANGER,
    params={"arg": "the string to reverse"},
    undo="Read the string and write its characters in reverse order.",
)
def string_reverse(ctx, arg: str, optional: int = 5) -> str:
    """Reverses the given string and returns the result. Use when you need the string backwards."""
    try:
        reversed_str = arg[::-1]
        return reversed_str
    except Exception as e:
        raise ToolError(f"Failed to reverse string: {e}. Ensure 'arg' is a valid string.")